import { parseMhtml, parseIsamsHtml } from './isams-parser.js';
const $=id=>document.getElementById(id), input=$('mhtmlFile'), status=$('status'), report=$('report'), checks=$('checks');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let objectUrls=[];
function clearObjectUrls(){objectUrls.forEach(u=>URL.revokeObjectURL(u));objectUrls=[]}
function photoUrl(part){if(!part?.bytes)return'';const u=URL.createObjectURL(new Blob([part.bytes],{type:part.contentType||'image/jpeg'}));objectUrls.push(u);return u}
function showChecks(r,m){const a=[['MHTML parsed',true],['HTML found',!!m.html],['Classes found',r.classes.length>0],['Students found',r.totals.students>0],['No empty names',r.classes.every(c=>c.students.every(s=>s.surname||s.preferredName))],['Numbering column excluded',r.classes.every(c=>!c.headers.some(h=>/^\d+\.?$/.test(h)))],['Dynamic fields retained',r.classes.every(c=>c.headers.length>=2)]];checks.innerHTML=a.map(([x,p])=>`<div class="check ${p?'pass':'fail'}">${p?'✓':'✕'} ${esc(x)}</div>`).join('')}
function studentName(s){return [s.preferredName,s.surname].filter(Boolean).join(' ')||'Unnamed student'}
function photoCell(s,partMap){const part=s.photo?.file?partMap.get(s.photo.file):null;const src=photoUrl(part);return src?`<div class="photo-thumb"><img src="${src}" alt=""><span class="photo-ok">✓ matched</span></div>`:`<div class="photo-missing"><span>—</span><small>No matched photo</small></div>`}
function studentVerification(c,partMap){const rows=c.students.map(s=>`<div class="student-card ${s.photo?'matched':'missing'}"><div class="student-photo">${photoCell(s,partMap)}</div><div class="student-info"><strong>${esc(studentName(s))}</strong><span>${esc(s.surname||'')} ${s.preferredName?`· ${esc(s.preferredName)}`:''}</span><div class="student-fields">${c.headers.slice(0,5).map(h=>`<span><b>${esc(h)}:</b> ${esc(s.fields[h]||'—')}</span>`).join('')}</div></div></div>`).join('');return `<section class="verification"><div class="verification-head"><div><h3>Photo verification</h3><p>Check that the automatic photo matches are correct. Students without a matched photo are shown without an image.</p></div><div class="verification-count"><b>${c.photoReport.matched}</b> / ${c.students.length} matched</div></div><div class="student-grid">${rows}</div></section>`}
function unmatchedPhotos(c,partMap){const list=c.photoReport.unmatchedImages;if(!list.length)return `<section class="unmatched none"><h3>Unmatched photos</h3><p>All gallery JPEGs were matched to a student.</p></section>`;return `<section class="unmatched"><h3>Unmatched photos <span>${list.length}</span></h3><p>These photos were found in the gallery but could not be confidently linked to a student. Nothing has been assigned automatically.</p><div class="unmatched-grid">${list.map(x=>{const part=partMap.get(x.image.file),src=photoUrl(part);return `<div class="unmatched-card">${src?`<img src="${src}" alt="">`:'<div class="image-placeholder">No preview</div>'}<div><strong>${esc(x.image.label||'No gallery name')}</strong><small>${esc(x.reason==='ambiguous'?'Ambiguous name match':'No name match')}</small><code>${esc(x.image.file)}</code></div></div>`}).join('')}</div></section>`}
function classHtml(c,partMap){const rows=c.students.slice(0,50).map(s=>`<tr>${c.headers.map(h=>`<td>${esc(s.fields[h])}</td>`).join('')}</tr>`).join('');const p=c.photoReport;return `<article class="class"><div class="class-head"><div><div class="class-title">${esc(c.metadata['Set Name']||'Class '+c.ordinal)}</div><div class="class-meta">${esc(c.metadata['Subject']||'')} · ${esc(c.metadata['Grade Group']||'')}</div></div><div>${c.students.length} students</div></div><div class="tags">${Object.entries(c.metadata).filter(([,v])=>v).map(([k,v])=>`<span class="tag"><b>${esc(k)}:</b> ${esc(v)}</span>`).join('')}</div><div class="tags"><span class="tag">${p.galleryImages} JPEGs</span><span class="tag good">${p.matched} matched</span><span class="tag ${p.studentsWithoutPhoto?'warn':''}">${p.studentsWithoutPhoto} without photo</span><span class="tag ${p.unmatchedImages.length?'warn':''}">${p.unmatchedImages.length} unmatched</span></div>${studentVerification(c,partMap)}${unmatchedPhotos(c,partMap)}<details class="raw-data"><summary>Student data table</summary><div class="table-wrap"><table class="student-table"><thead><tr>${c.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></details></article>`}
input.addEventListener('change',async()=>{const f=input.files?.[0];if(!f)return;clearObjectUrls();checks.innerHTML='';report.textContent='Parsing…';status.className='status';status.textContent=`Reading ${f.name}…`;try{const raw=await f.text(),m=parseMhtml(raw),r=parseIsamsHtml(m.html,m.binaryParts),partMap=new Map(m.binaryParts.map(p=>{const key=p.location.split('/').pop();return [decodeURIComponent(key),p]}));report.innerHTML=`<div class="summary"><div class="metric"><strong>${r.totals.classes}</strong>classes</div><div class="metric"><strong>${r.totals.students}</strong>students</div><div class="metric"><strong>${r.totals.galleryImages}</strong>JPEG gallery images</div><div class="metric"><strong>${r.totals.matchedPhotos}</strong>photos matched</div></div>${r.classes.map(c=>classHtml(c,partMap)).join('')}`;showChecks(r,m);status.className='status ok';status.textContent=`Complete. ${m.parts.length} MIME parts; ${m.binaryParts.length} JPEG parts; ${r.totals.classes} classes; ${r.totals.students} students.`;window.__parserResult=r}catch(e){console.error(e);status.className='status bad';status.textContent='Parser failed: '+(e.stack||e.message||e);report.innerHTML='<div class="empty">See the error above.</div>'}});
